FROM golang:1.21 as build
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cloudrun ./cmd/main.go

FROM alpine
WORKDIR /app
COPY --from=build /app/cloudrun .
COPY --from=build /app/.env .
RUN apk add --no-cache ca-certificates
ENTRYPOINT ["./cloudrun"]